New widget "Select Cuda Device" added
supervisely/supervisely pull request #1104
Opened 2024-09-03 23:24 UTC by vorozhkog

2024-09-04 13:12 UTC, iwatkot submitted a review, later dismissed

2024-09-04 13:12 UTC, iwatkot commented on supervisely/app/widgets/select_cuda/select_cuda.py
> +# from supervisely.decorators.profile import timeit
Remove unused import

2024-09-04 13:12 UTC, iwatkot commented on supervisely/app/widgets/select_cuda/select_cuda.py
> +    def set_device(self, value: str) -> None:
Add expected values of argument (e.g. 'cuda:0', 'cpu', etc.).

2024-09-04 13:38 UTC, cxnt commented on supervisely/app/widgets/select_cuda/select_cuda.py
> +                "right_text": f"{convert_to_gb(device_memory['available'])} / {convert_to_gb(device_memory['total'])} GB",
reserved / total
"right_text": f"{convert_to_gb(device_memory['reserved'])} / {convert_to_gb(device_memory['total'])} GB",

2024-09-05 09:50 UTC, iwatkot requested changes

2024-09-05 12:16 UTC, merged