make-tqdm-progress
supervisely/supervisely pull request #502
Opened 2023-04-03 15:32 UTC by peixed351

2023-04-26 12:53 UTC, mkolomeychenko requested changes
Посмотри и поправь с учетом комментов

2023-04-26 12:53 UTC, mkolomeychenko commented on supervisely/api/advanced_api.py
> -        """
Докстринги поломаются в доке публичной, в них нельзя оставлять пробел, лучше либо не менять либо хотя бы одну фразу простенькую написать

2023-04-26 12:53 UTC, mkolomeychenko commented on supervisely/api/file_api.py
> +            and progress_cb is not Callable
Оно прям is not callable работает? Там не нужно писать type(progress_cb)?

2023-04-26 12:53 UTC, mkolomeychenko commented on supervisely/api/image_api.py
> -            ds_kiwi_id = 1233
А зачем мы пример меняли, он кривой? Если меняем -то может именования поменять?

2023-04-26 12:53 UTC, mkolomeychenko commented on supervisely/api/project_api.py
> -from collections import defaultdict
Нэто нигде не использовалось?

2023-04-26 12:53 UTC, mkolomeychenko commented on supervisely/api/project_api.py
> +        :type progress_cb: tqdm, optional
В таких аннотациях не нужно писать что tqdm or callable?

2023-04-26 12:53 UTC, mkolomeychenko commented on supervisely/api/team_api.py
> +        if (
Такая проверка много где используется, может ее в питон файл с классом прогресса как функцию вынести и ее ве
Зде одинаковую использовать?

2023-04-26 13:48 UTC, grokhi commented on supervisely/api/file_api.py
> +            and progress_cb is not Callable
решил убрать, т.к. tqdm_sly всегда Callable благодаря self.__call__()

2023-04-26 14:06 UTC, grokhi commented on supervisely/api/project_api.py
> -from collections import defaultdict
строчка не запарсилась когда я реформировал шапку с импортами
![image](https://user-images.githubusercontent.com/78355358/234601370-fe042dcf-1db5-4472-86a4-a6d17aae0301.png)

2023-04-26 14:14 UTC, grokhi commented on supervisely/api/project_api.py
> +        :type progress_cb: tqdm, optional
согласен, tqdm or callable более корректный с точки зрения Legacy, но если быть предельно точным, то любой инстанс tqdm_sly будет Callable

2023-04-26 14:19 UTC, grokhi commented on supervisely/api/team_api.py
> +        if (
используется всего в двух местах, тем более проверку на callable я решил убрать, т.к. она здесь бесполезна: callable(Progress.update) == callable(tqdm_sly) == True

2023-04-27 08:29 UTC, mkolomeychenko commented on supervisely/api/team_api.py
> +        if progress_cb is not None and isinstance(progress_cb, tqdm):
неправильный код

2023-04-27 08:29 UTC, mkolomeychenko commented on supervisely/api/team_api.py
> +                if progress_cb is not None and isinstance(progress_cb, tqdm):
непрвавильный код

2023-04-27 08:29 UTC, mkolomeychenko commented on supervisely/api/video/video_annotation_api.py
> -from typing import List, Dict, Optional, Callable
по какой логике меняются импорты, для чего?

2023-04-27 08:29 UTC, mkolomeychenko commented on supervisely/api/video/video_api.py
> +        def _callback(monitor, progress):
вопрос к изменению логики

2023-04-27 08:29 UTC, mkolomeychenko commented on supervisely/api/volume/volume_api.py
> -        for (plane, dimension) in zip(planes, np_data.shape):
это автоматом изменилось?

2023-04-27 08:29 UTC, mkolomeychenko commented on supervisely/task/progress.py
> +            if monitor.bytes_read == 8192:
а что это за магическая константа?

2023-04-27 08:29 UTC, mkolomeychenko commented on supervisely/task/progress.py
> +            if self._total_monitor_size > self.total:
не понимаю этот код

2023-04-27 08:29 UTC, mkolomeychenko commented on supervisely/project/video_project.py
> +from tqdm import tqdm
зачем реструктурировать импорты?

2023-04-27 08:29 UTC, mkolomeychenko commented on supervisely/api/image_api.py
> -import json
по какой логике изменяются импорты?

2023-04-27 09:12 UTC, mkolomeychenko requested changes

2023-04-27 09:55 UTC, grokhi commented on supervisely/api/volume/volume_api.py
> -        for (plane, dimension) in zip(planes, np_data.shape):
да. это black formatter

2023-04-27 14:17 UTC, merged