stl to nrrd on upload + volume geometries
supervisely/supervisely pull request #684
Opened 2023-09-14 22:51 UTC by GoldenAnpu

WIP

2023-09-19 11:37 UTC, mkolomeychenko requested changes

2023-09-19 11:37 UTC, mkolomeychenko commented on supervisely/api/volume/volume_annotation_api.py
> +        sf_geometries: Dict = None,
Dict Types

2023-09-19 11:37 UTC, mkolomeychenko commented on supervisely/api/volume/volume_annotation_api.py
> +        :type key_id_map: Dict, optional
?

2023-09-19 11:37 UTC, mkolomeychenko commented on supervisely/api/volume/volume_annotation_api.py
> +        sf_geometries: Dict = None,
ask Umar to change default class shape in DICOM volumes to Mask3D

use case 1 - main
obj = VolumeObject(tumor_class, mask_3d =  np3d_or_"~/home/mask.nrrd", tags=[])
ann = VolumeAnnotation(volume_size, objects=[obj1, obj2, ...], tags=[])
ann = ann.add_objects(objects=[a1, a2, a3])

api.volume.annotation.append(volume_id, ann)
api.volume.annotation.append_objects(volume_id, objects=[a1, a2, a3])

use case 2
obj = VolumeObject(tumor_class)
obj.add_mask_2d(plane_name: Literal["sag", "cor" ....], slice=123, sly.Bitmap() or "dsdasd.png" or np array 01-TF)


### obj.add_2d_label(plane_name: Literal["sag", "cor" ....], slice=123, sly.XXXGeometry)


ann = VolumeAnnotation(volume_size, objects=[obj1, obj2, ...])
api.volume.annotation.append(ann)
api.volume.annotation.append_objects(objects=[a1, a2, a3])

### later:
### VolumeFigure - actual only for 2d shapes
### obj.add_2d_figure(sly.Rectangle(dfsfdsf), plane, slice)


------------------------------------------------------
ann = VolumeAnnotation(...)
obj = VolumeObject(tumor_class)
tumor_mask_3d = sly.Mask3d(np 3d array //// "~/home/mask.nrrd" //// )
rectagle = sly.Rectangle(...)



obj.add_figure(tumor_mask_3d)

2023-09-19 11:48 UTC, mkolomeychenko requested changes

2023-09-19 11:48 UTC, mkolomeychenko commented on supervisely/io/fs.py
> +        required_value = get_nested_dicts_data(nested_dict, 'first_level', 'second_level', 'third_level_2')
nested_dict['first_level']['second_level']['third_level_2']

2023-09-19 11:48 UTC, mkolomeychenko commented on supervisely/io/fs.py
> +        required_value = get_nested_dicts_data(nested_dict, 'first_level', 'second_level', 'third_level_2')
nested_dict.get('first_level', {}).get(['second_level', {}).get('third_level_2', {})

2023-09-20 11:40 UTC, GoldenAnpu commented on supervisely/api/volume/volume_annotation_api.py
> +        sf_geometries: Dict = None,
добавил еще и api.project.append_classes(porject_id, [new_class])

2023-09-20 11:42 UTC, GoldenAnpu commented on supervisely/api/volume/volume_annotation_api.py
> +        :type key_id_map: Dict, optional
убрал вовсе, теперь фигуры приходят с 3д аннотациями, геометрии забираются из них и аплодятся уже в самом конце глубоко внутри

2023-09-20 11:45 UTC, GoldenAnpu commented on supervisely/io/fs.py
> +        required_value = get_nested_dicts_data(nested_dict, 'first_level', 'second_level', 'third_level_2')
removed at all

2023-09-20 11:45 UTC, GoldenAnpu commented on supervisely/api/volume/volume_annotation_api.py
> +import supervisely
fixed

2023-09-21 18:15 UTC, mkolomeychenko requested changes

2023-09-21 18:15 UTC, mkolomeychenko commented on supervisely/api/volume/volume_annotation_api.py
> +            new_f_id = max_f_id + (10 ** (len(str(max_f_id)) - 1)) + random.randint(100, 999)
server ids can not be generated on client side?

2023-09-21 18:15 UTC, mkolomeychenko commented on supervisely/api/volume/volume_figure_api.py
> +        if not figures:
?

2023-09-21 18:15 UTC, mkolomeychenko commented on supervisely/api/volume/volume_figure_api.py
> -    # def interpolate_batch(
keep

2023-09-21 18:15 UTC, mkolomeychenko commented on supervisely/api/volume/volume_figure_api.py
>          if figures_count == 0:
if len() == 0

2023-09-21 18:15 UTC, mkolomeychenko commented on supervisely/api/volume/volume_figure_api.py
> +        if not spatial_figures:
?

2023-09-21 18:15 UTC, mkolomeychenko commented on supervisely/geometry/mask_3d.py
> +    def to_figure_from_file(figure, file_path: str):
from_file

2023-09-21 18:15 UTC, mkolomeychenko commented on supervisely/geometry/mask_3d.py
> +    def to_figure_from_bytes(figure, geometry_bytes: bytes):
from_bytes

2023-09-21 18:15 UTC, mkolomeychenko commented on supervisely/geometry/mask_3d.py
> +    def to_figure_from_array(cls, figure, data_array: np.ndarray) -> None:
from_np

2023-09-21 18:35 UTC, mkolomeychenko commented on supervisely/volume/stl_converter.py
> +def save_to_nrrd_file_on_upload(interpolation_dir: str) -> List[str]:
convert_str_to_nrrd

2023-09-21 18:35 UTC, mkolomeychenko commented on supervisely/volume/stl_converter.py
> +def save_to_nrrd_file_on_upload(interpolation_dir: str) -> List[str]:
str_to_nrrd

2023-09-21 18:35 UTC, mkolomeychenko commented on supervisely/volume/stl_converter.py
> +        volume_path = os.path.dirname(stl_path.replace(interpolation_dir_name, volume_dir_name))
interpolation_dir_name - ???

2023-09-21 18:35 UTC, mkolomeychenko commented on supervisely/volume_annotation/volume_object.py
> +        if mask_3d:
is not None

2023-09-21 18:35 UTC, mkolomeychenko commented on supervisely/volume_annotation/volume_annotation.py
> +                    "There is no spatial figure in 'VolumeObject'",
3D mask for object is not defined

2023-09-21 18:35 UTC, mkolomeychenko commented on supervisely/volume_annotation/volume_annotation.py
> +        self = self.clone(objects=collection)
new_ann = self.clone(objects=collection)
new_ann.spatial_figures.extend(sf_figures)
return new_ann

2023-09-21 18:35 UTC, mkolomeychenko commented on supervisely/volume/stl_converter.py
> +volume_dir_name = "volume"
hardcode

2023-09-21 18:35 UTC, mkolomeychenko commented on supervisely/volume/stl_converter.py
> +def save_to_nrrd_file_on_upload(interpolation_dir: str) -> List[str]:
stl_to_nrrd(stl_path, nrrd_path):
....

2023-09-21 18:39 UTC, mkolomeychenko requested changes

2023-09-21 18:39 UTC, mkolomeychenko commented on supervisely/api/volume/volume_annotation_api.py
> +        mask_dirs=None,
remove?

2023-09-28 13:15 UTC, mkolomeychenko requested changes

2023-09-28 13:15 UTC, mkolomeychenko commented on supervisely/volume_annotation/volume_figure.py
> +    def set_geometry(self, new_geometry: Mask3D) -> None:
_set_3d_geometry

2023-09-28 13:15 UTC, mkolomeychenko commented on supervisely/volume_annotation/volume_figure.py
> +        if new_geometry.name() != Mask3D.name():
type

2023-09-28 13:15 UTC, mkolomeychenko commented on supervisely/volume_annotation/volume_figure.py
> +        if new_geometry.name() != Mask3D.name():
isinstance

2023-09-28 13:15 UTC, mkolomeychenko commented on supervisely/project/volume_project.py
> -def load_figure_data(
why?

2023-09-28 13:15 UTC, mkolomeychenko commented on supervisely/geometry/mask_3d.py
> +            return cls(data=np.random.randint(2, size=(3, 3, 3), dtype=np.bool_))
?

2023-09-29 12:58 UTC, GoldenAnpu commented
Create new PR based on this one after https://github.com/supervisely/supervisely/pull/699 will be merged.
Need to transfer just changes that described in this PR

2023-10-02 18:45 UTC, GoldenAnpu commented
Merge this after https://github.com/supervisely/supervisely/pull/699 will be merged.

2023-10-04 21:55 UTC, closed without merging