add field projectSettings to meta.json
supervisely/supervisely pull request #810
Opened 2023-12-22 13:36 UTC by grokhi

2023-12-27 12:55 UTC, mkolomeychenko requested changes

2023-12-27 12:55 UTC, mkolomeychenko commented on supervisely/api/project_api.py
> +            parent_project_tag_name = s[PMJsonF.MULTI_VIEW][PMJsonF.TAG_NAME]
parent?

2023-12-27 12:55 UTC, mkolomeychenko commented on supervisely/api/project_api.py
> +                                PMJsonF.VIEWS_SYNCED: json_settings["groupImagesSync"],
VIEWS_ARE_SYNCED

2023-12-27 12:55 UTC, mkolomeychenko commented on supervisely/project/project_meta.py
> +        s = sly.ProjectSettings(
separate example

2023-12-27 12:55 UTC, mkolomeychenko commented on supervisely/project/project_meta.py
> +            multiview_tag_id= 3322,
defv uses only names be default

2023-12-27 19:06 UTC, mkolomeychenko requested changes

2023-12-27 19:06 UTC, mkolomeychenko commented on supervisely/project/project_settings.py
> +        }
def from_json(d, project_meta):
       deserializatiojn + validation

2023-12-27 19:06 UTC, mkolomeychenko commented on supervisely/project/project_meta.py
> +    MULTI_VIEW = "multiView"
move to Project settings class

2023-12-27 19:06 UTC, mkolomeychenko commented on supervisely/project/project_meta.py
> +            self._project_settings = project_settings.to_json(ProjectMetaJsonFields)
project_settings.to_json()

2023-12-27 19:06 UTC, mkolomeychenko commented on supervisely/project/project_meta.py
>          self._project_type = project_type
self._project_type : dict -> ProjectSettings

2023-12-29 14:45 UTC, mkolomeychenko requested changes

2023-12-29 14:45 UTC, mkolomeychenko commented on supervisely/project/project_settings.py
> +    def from_json(cls, data: Dict) -> "ProjectSettings":
from __future__ import annotations

2023-12-29 14:45 UTC, mkolomeychenko commented on supervisely/api/project_api.py
> +    ) -> Dict[str, str]:
ProjectSettings

2023-12-29 17:17 UTC, mkolomeychenko requested changes

2023-12-29 17:17 UTC, mkolomeychenko commented on supervisely/project/project_settings.py
> +        self.multiview_enabled = multiview_enabled
if self.multiview_enabled is True and multiview_tag_name is None:
    raise provide ....

if multiview_is_synced is True and multiview_enabled is False:
    raise provide ....

2023-12-29 17:17 UTC, mkolomeychenko commented on supervisely/project/project_meta.py
> +
if self._project_settings is not None:
      if self._tag_metas.get_tag_meta_by_name(self._project_settings.tag_name) is None:  
            . ...create tag meta directly .... see docstrings for example

2023-12-29 17:22 UTC, mkolomeychenko requested changes

2023-12-29 17:22 UTC, mkolomeychenko commented on supervisely/project/project_settings.py
> +        )
def validate(meta: ProjectMeta):
     check that tag by name exists and 
           if id is not none => id == existing id

2024-01-04 08:11 UTC, grokhi commented on supervisely/project/project_settings.py
> +        self.multiview_enabled = multiview_enabled
1. комбинация self.multiview_enabled is True and multiview_tag_name is None допустима, т.к. идентификация group_tag мб и по multiview_tag_id
2.  added

2024-01-04 08:15 UTC, grokhi commented on supervisely/project/project_settings.py
> +        self.multiview_enabled = multiview_enabled
добавил ворнинги вместо raise т.к. в веб-морде ProjectSettings существует возможность проставить multiview_is_synced is True and multiview_enabled is False

2024-01-04 08:15 UTC, grokhi commented on supervisely/project/project_settings.py
> +        self.multiview_enabled = multiview_enabled
![image](https://github.com/supervisely/supervisely/assets/78355358/97ec01d3-cd92-43a7-9ab0-c843088a4e98)

2024-01-04 08:38 UTC, grokhi commented on supervisely/project/project_settings.py
> +        )
отказался от идеи в пользу ProjectMeta().validate_project_settings()

m.project_settings.validate(meta=m) # нарушает инкапсуляцию, передавая методы ProjectMeta в ProjectSettings
m.validate_project_settings() # обеспечивает сокрытие методов ProjectMeta

2024-01-04 09:50 UTC, grokhi commented on supervisely/project/project_meta.py
> +
Предлагаю вынести опцию добавления несуществующего тега в метод ProjectMeta

 self.validate_project_settings(add_multi_tag_meta=False)
 
 т.е. по умолчанию в init выскочит ошибка. однако всегда можно будет вызвать метод валидации и вернуть обновленную мету (сохраняется иммутабельность класса)
 
m =  self.validate_project_settings(add_multi_tag_meta=True)

2024-01-04 12:10 UTC, grokhi commented on supervisely/api/project_api.py
Добавил эти строчки для того, чтобы выбранные опции в веб-интерфейсе Settings->Visuals в точности отображались в meta.json

2024-01-04 12:11 UTC, grokhi commented on supervisely/api/project_api.py
> +
Добавил эти строчки для того, чтобы выбранные опции в веб-интерфейсе Settings->Visuals в точности отображались в meta.json

2024-01-04 12:12 UTC, grokhi commented on supervisely/api/project_api.py
> +
new_s.to_json() здесь не подойдет, т.к. он для meta.json

2024-01-04 12:15 UTC, grokhi commented on supervisely/api/project_api.py
> +
![image](https://github.com/supervisely/supervisely/assets/78355358/e0a54492-6b1e-4284-b66f-ed70a134fa8d)

2024-01-04 14:51 UTC, mkolomeychenko commented on supervisely/project/project_meta.py
> +                        f"The multi-view tag '{mtag_name}' was not found in the '{ProjectMetaJsonFields.TAGS}' field. Please specify the matching tag in the 'meta.json' file."
The multi-view tag '{mtag_name}' was not found in the project meta. Please directly add the tag meta that will be used for image grouping for multi-view labeling interface.

2024-01-04 16:04 UTC, grokhi commented on supervisely/project/project_meta.py
> +        self._project_settings.validate(self, add_multi_tag_meta=False)
Поменял на add_multi_tag_meta=False

2024-01-04 18:24 UTC, grokhi commented on supervisely/project/project_settings.py
> +            if mtag_name is None:
case1: multiview_tag_name:str, multiview_tag_id:any -> identification by name
case2: multiview_tag_name=None, multiview_tag_id:int -> identification by id
case3: multiview_tag_name=None, multiview_tag_id=None -> no identification, but its accaptable

2024-01-04 18:48 UTC, merged