Upgrade figure api
supervisely/supervisely pull request #820
Opened 2023-12-28 16:05 UTC by cxnt

2024-01-10 11:59 UTC, cxnt commented on supervisely/api/api.py
> +        self.figure = figure_api.FigureApi(self)
мы это обсуждали, но я не очень понимаю как тут поменять импорт/название

2024-01-22 11:36 UTC, cxnt commented on supervisely/api/entity_annotation/figure_api.py
> +        return super()._convert_json_info(info, True)
поставил True, потому что падает взависимости от того это фигура картинки или видео. Если картинки падает с ключом что "frame" не найден, потому что в поле 'meta' у картинки пустой dict

2024-01-22 13:37 UTC, cxnt commented on supervisely/api/api.py
> +        self.figure = figure_api.FigureApi(self)
api.video.annotation.figure

2024-01-24 11:56 UTC, mkolomeychenko commented on supervisely/api/labeling_job_api.py
> +    def get_annotation_by_image_id(self, id: int, image_id: int) -> Annotation:
def get_annotations(self,  id, image_ids)

2024-01-24 11:56 UTC, mkolomeychenko commented on supervisely/api/labeling_job_api.py
> +            for figure in self._api.image.figure.get_list(job_info.dataset_id)
reimplement

2024-01-24 11:56 UTC, mkolomeychenko commented on supervisely/api/labeling_job_api.py
> +        image = self._api.image.get_info_by_id(image_id)
tags?

2024-01-24 11:56 UTC, mkolomeychenko commented on supervisely/api/labeling_job_api.py
> +    def get_annotation_by_image_id(self, id: int, image_id: int) -> Annotation:
project_meta=None

2024-01-24 11:56 UTC, mkolomeychenko commented on supervisely/api/labeling_job_api.py
> +        job_meta = self.get_project_meta(id)
if not none

2024-01-24 16:09 UTC, mkolomeychenko requested changes

2024-01-24 16:09 UTC, mkolomeychenko commented on supervisely/api/entity_annotation/figure_api.py
> +        file_infos = []
name

2024-01-24 16:09 UTC, mkolomeychenko commented on supervisely/api/entity_annotation/figure_api.py
> +        file_infos = []
images_figures?

2024-01-24 16:09 UTC, mkolomeychenko commented on supervisely/api/entity_annotation/figure_api.py
> +        file_infos = []
List[List]
Dict[int->List]

2024-01-24 16:09 UTC, mkolomeychenko commented on supervisely/api/entity_annotation/figure_api.py
> +    def get_list(
download

2024-01-24 17:00 UTC, merged