Data nodes deploy yolov8
supervisely/supervisely pull request #821
Opened 2023-12-29 15:00 UTC by cxnt

2024-01-09 15:58 UTC, cxnt commented on supervisely/api/agent_api.py
> +    def get_list_available(
название возможно стоит поменять

2024-01-09 16:03 UTC, cxnt commented on supervisely/nn/inference/checkpoints/__init__.py
> +from supervisely.nn.inference.checkpoints import (
не уверен как тут лучше сделать и как это будут использовать

можно прописывать импорт полность, но тогда дублируется слово checkpoints и наверное это не круто

```python
sly.nn.checkpoints.yolov8.list_checkpoints()
```
можно импортировать просто файлик yolov8 и вызывать вот так, но если из название убрать метод то не будет понятно что он делает
```python
from supervisely.nn.inference.checkpoints import yolov8
yolov8.list_checkpoints()
```

наверное лучше сделатьпросто supervisely.nn.checkpoints и отсюда брать?

2024-01-09 16:05 UTC, cxnt commented on supervisely/nn/inference/checkpoints/mmdetection3.py
> +    raise NotImplementedError
тут работает всё, но парсится питоновский файлик, который я скачиваю как txt и читаю, пока закоментил всё

2024-01-11 11:47 UTC, mkolomeychenko requested changes

2024-01-11 11:47 UTC, mkolomeychenko commented on supervisely/api/agent_api.py
> +    AnnotationInfo
?

2024-01-11 11:47 UTC, mkolomeychenko commented on supervisely/api/agent_api.py
> +            "agents.list", {"teamId": team_id, "filter": filters or []}
format?

2024-01-11 11:47 UTC, mkolomeychenko commented on supervisely/api/agent_api.py
> +    ):
?

2024-01-11 11:47 UTC, mkolomeychenko commented on supervisely/api/agent_api.py
> +    ):
return value annotation

2024-01-11 11:47 UTC, mkolomeychenko commented on supervisely/api/agent_api.py
> +    updated_at: str
gpu info (optional)

2024-01-11 11:47 UTC, mkolomeychenko commented on supervisely/api/agent_api.py
> +        return r
AgentInfo

2024-01-11 11:47 UTC, mkolomeychenko commented on supervisely/api/agent_api.py
> +        return r
convert_json_info - ignore missing values = True

2024-01-11 11:47 UTC, mkolomeychenko commented on supervisely/api/agent_api.py
> +        return r
def _convert_json_info(self, info: dict, skip_missing=False):

2024-01-11 11:47 UTC, mkolomeychenko commented on supervisely/api/agent_api.py
> +    ):
check tokein info for public agents that were run from admin account

2024-01-11 11:47 UTC, mkolomeychenko commented on supervisely/api/agent_api.py
> +    ):
full access including token OR you can run apps on them?

2024-01-11 11:47 UTC, mkolomeychenko commented on supervisely/api/agent_api.py
> +    ):
more flags

2024-01-11 11:47 UTC, mkolomeychenko commented on supervisely/api/agent_api.py
> +    def get_list_available(
get_list_

2024-01-11 11:47 UTC, mkolomeychenko commented on supervisely/app/widgets/nodes_flow/nodes_flow.py
> +        self._node_removed_handled = True
init?

2024-01-11 11:47 UTC, mkolomeychenko commented on supervisely/app/widgets/trained_models_selector/trained_models_selector.py
> +        def artifacts_paths(self) -> List[str]:
artifacts -> checkpoints?

2024-01-11 11:47 UTC, mkolomeychenko commented on supervisely/app/widgets/trained_models_selector/trained_models_selector.py
> +        print(self._changes_handled)
?

2024-01-11 11:47 UTC, mkolomeychenko commented on supervisely/nn/inference/checkpoints/checkpoint.py
> +CheckpointInfo = namedtuple(
class?

2024-01-11 11:47 UTC, mkolomeychenko commented on supervisely/app/widgets/trained_models_selector/trained_models_selector.py
> +        checkpoint_infos: List[CheckpointInfo],
checkpoints

2024-01-11 11:47 UTC, mkolomeychenko commented on supervisely/nn/inference/checkpoints/__init__.py
> +from supervisely.nn.inference.checkpoints import (
sly.nn.checkpoints.get_list(team_id=123, framework=Literal(yolov8, yolov5-v2, mmdetection-3, ))

2024-01-11 11:47 UTC, mkolomeychenko commented on supervisely/nn/inference/checkpoints/__init__.py
> +from supervisely.nn.inference.checkpoints import (
sly.nn.checkpoints.yolov8.get_list()

2024-01-22 09:12 UTC, cxnt commented on supervisely/api/agent_api.py
> +        return super()._convert_json_info(info, True)
поставил всегда True потому что методы 'agents.list' и 'agents.available' возвращают немного разные поля

2024-01-22 19:34 UTC, mkolomeychenko requested changes

2024-01-22 19:34 UTC, mkolomeychenko commented on supervisely/app/widgets/nodes_flow/nodes_flow.py
> +    def node_removed(self, func):
callable

2024-01-22 19:34 UTC, mkolomeychenko commented on supervisely/app/widgets/trained_models_selector/trained_models_selector.py
> +    def select_row(self, row_index):
annotation

2024-01-22 19:34 UTC, mkolomeychenko commented on supervisely/nn/inference/inference.py
> +        def deploy_nn_serving(response: Response, request: Request):
1. run app via api (with autostart=False)
2. api to deploy model checkpoint -> checkpoint has to be downloaded to directory -> deploy
3. API to stop deployed model and revert to initial state (like after 1)

2024-03-12 10:27 UTC, closed without merging