Moved from script to Python for Supervisely VPN connection
supervisely/supervisely pull request #874
Opened 2024-02-12 16:55 UTC by iwatkot

2024-02-13 10:18 UTC, tonybart1337 requested changes

2024-02-13 10:18 UTC, tonybart1337 commented on supervisely/app/development/development.py
> +def supervisely_vpn_network(
у нас есть где-нить проверка что wg-quick доступен? на случай если пользователь забыл установить wireguard

2024-02-13 11:46 UTC, iwatkot commented on supervisely/app/development/development.py
> +        logger.info("Connection to Supervisely VPN has been established successfully.")
Готово

2024-02-13 11:46 UTC, iwatkot commented on supervisely/app/development/development.py
> +def supervisely_vpn_network(
Готово

2024-02-13 14:01 UTC, tonybart1337 requested changes

2024-02-13 14:01 UTC, tonybart1337 commented on supervisely/app/development/development.py
> +VPN_IP = "http://10.8.0.1"
gateway это динамическая настройка и она прилетает ниже в ответ на register метод:
```python
# ${ip};${publicKey};${vpnEndpoint};${vpnSubnetBase};${vpnGateway}`
ip, server_public_key, server_endpoint, *_ = response.text.split(";")
```

2024-02-20 14:10 UTC, tonybart1337 commented
perfection. я бы только подумал над тем чтобы сохранять состояние от register в json файлик и делать wg-quick down только когда оно реально поменялось, но т.к. в wireguard по сути нет никакого соединения, то оно не должно влиять на performance разработки приложения.

имею в виду когда меняешь код, то мы интерфейс wg отключаем и включаем и там выполняется handshake, но это все очень быстро происходит и не должно влиять, поэтому я бы оставил как есть

2024-02-20 14:15 UTC, tonybart1337 approved these changes

2024-02-21 09:22 UTC, merged